SO-973 - allow add team members before rego
digitalnsw/buy-nsw-front pull request #177
Opened 2020-08-18 23:47 UTC by adohall

2020-08-19 06:36 UTC, armansa requested changes

2020-08-19 06:36 UTC, armansa commented on app/templates/seller-dashboard.hbs
> +        {{#link-to "team-members"}}
It still requires a condition:
if this.model.seller
  show link
else
  show the other box

2020-08-19 23:34 UTC, adohall commented on app/templates/seller-dashboard.hbs
> +        {{#link-to "team-members"}}
Done. Condition added, so that all sellers, even those who haven't finished registration, can add team members. Note - there is no alternate content for non-sellers.

2020-08-20 01:55 UTC, armansa approved these changes

2020-08-20 01:55 UTC, merged